stages:
  - install
  - lint
  - test
  - build
  - docker-build
  - deploy

variables:
  NODE_ENV: production
  PNPM_HOME: /root/.pnpm
  DOCKER_DRIVER: overlay2

default:
  image: node:18

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install

install:
  stage: install
  script:
    - echo "pnpm install already done in before_script"

lint:
  stage: lint
  script:
    - pnpm lint

test:
  stage: test
  script:
    - pnpm test

build-frontend:
  stage: build
  script:
    - pnpm build --filter=frontend...
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-backend:
  stage: build
  script:
    - pnpm build --filter=backend...
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

docker-build-frontend:
  stage: docker-build
  image: docker:20
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -f apps/frontend/Dockerfile -t $DOCKER_IMAGE/frontend:latest .
    - docker tag $DOCKER_IMAGE/frontend:latest $DOCKER_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE/frontend:latest
    - docker push $DOCKER_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

docker-build-backend:
  stage: docker-build
  image: docker:20
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -f apps/backend/Dockerfile -t $DOCKER_IMAGE/backend:latest .
    - docker tag $DOCKER_IMAGE/backend:latest $DOCKER_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE/backend:latest
    - docker push $DOCKER_IMAGE/backend:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-frontend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - scp scripts/deploy-frontend.sh $DEPLOY_USER@$DEPLOY_HOST:~/deploy-frontend.sh
    - ssh $DEPLOY_USER@$DEPLOY_HOST "chmod +x ~/deploy-frontend.sh && ~/deploy-frontend.sh"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-backend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - scp scripts/deploy-backend.sh $DEPLOY_USER@$DEPLOY_HOST:~/deploy-backend.sh
    - ssh $DEPLOY_USER@$DEPLOY_HOST "chmod +x ~/deploy-backend.sh && ~/deploy-backend.sh"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
