stages:
  - install
  - docker-build
  - deploy

include:
  - '.ci/common-variables.yml'
  - '.ci/jobs/docker-build-frontend.yml'
  - '.ci/jobs/docker-build-backend.yml'
  - '.ci/jobs/deploy-backend.yml'
