version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medinow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend-dev
    ports:
      - "4001:4000"
    env_file:
      - apps/backend/.env
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - apps/frontend/.env
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend-network:
    driver: bridge