services:
  postgres:
    image: postgres:17
    container_name: postgres-prod
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medinow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network

  backend:
    image: grapefruitgreentealoe/medinow-backend:latest
    container_name: backend-prod
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env
    networks:
      - backend-network

volumes:
  postgres_data:
  redis_data:

networks:
  backend-network:
    driver: bridge