version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-dev
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medinow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend-network

  backend:
    image: grapefruitgreentealoe/medinow-backend:dev
    container_name: backend-dev
    depends_on:
      - postgres
      - redis
    ports:
      - '4001:4000'
    env_file:
      - /home/cloud/.env
    networks:
      - backend-network

volumes:
  postgres_data:
  redis_data:

networks:
  backend-network:
    driver: bridge
    internal: false #internal false 추가하여 네트워크 생성으로 인한 dns 영향 제거
