#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo "🚀 pre-push 훅 실행됨!"

# pnpm을 시스템이 아니라 로컬 node_modules에서 실행
./node_modules/.bin/pnpm lint
./node_modules/.bin/pnpm test
./node_modules/.bin/pnpm build --filter=frontend...
./node_modules/.bin/pnpm build --filter=backend...